import './main.css';

function Main() {
    return(
        <div className="main-wrapper">
            main main main mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain main
            main main main mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain main
main main main mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain main
main main main mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain main
            main main main mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain main
            main main main mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain main
            main main main mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain main
            main main main mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain main
            main mai            main main main mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain main
            main main main mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain main
            main main main mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain main
            main main main mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain main
            main main main mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain main
            main main main mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain main
n main mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain main
 main main main mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain mainmain main
        </div>
    );
}

export default Main;